# ありえないvhostとかIP直の場合403にする
server {
  server_name "";
  listen 80 default_server;
  listen [::]:80 default_server;

  location / {
    return 403;
  }
}

server {
  server_name "";

  listen 443 ssl backlog=4096 default_server;
  listen [::]:443 ssl backlog=4096 default_server;
  listen 443 quic reuseport default_server;
  listen [::]:443 quic reuseport default_server;

  http2 on;

  ssl_certificate     /home/www/lego/ecdsa/certificates/catatsuy.org.fullchain.pem;
  ssl_certificate_key /home/www/lego/ecdsa/certificates/catatsuy.org.key;
  ssl_certificate     /home/www/lego/rsa/certificates/catatsuy.org.fullchain.pem;
  ssl_certificate_key /home/www/lego/rsa/certificates/catatsuy.org.key;

  location / {
    return 403;
  }
}
